### ISSUE TITLE
Poetry fails to install pymkv2 due to an issue detecting a valid version of iso-639

### ISSUE THREAD

**Issue by GH0STDATA** [GitBib/pymkv2#18]
**Describe the bug**
Due to iso-639 being a dependency, I cannot add pymkv2 to my poetry project. There is a bug where iso-639 v0.4.5 cannot be detected by poetry.

**To Reproduce**
1. Add pymkv2 to `pyproject.toml`
1. Run `poetry install`

**Expected behavior**

Poetry should be able to install pymkv2 with no errors.

**Screenshots**

![poetry-error](https://github.com/user-attachments/assets/1db9a9dd-3462-45e9-8af0-5962296f1fca)

**Software (please complete the following information):**
 - OS: Windows 11 x64
 - MKVToolNix version: v86.0

**Additional context**

I would recommend using python-iso639 instead as its more up-to-date and will most likely work with poetry with no issues: https://pypi.org/project/python-iso639/

**Comment by GitBib** [comment]
The replacement of iso-639 happened surprisingly fast. Therefore you can already use the new version [2.0.7](https://github.com/GitBib/pymkv2/releases/tag/2.0.7)

**Comment by GH0STDATA** [comment]
Thank you very much for the very fast fix!
