### ISSUE TITLE
mkvmerge_path str parameter can be limiting

### ISSUE THREAD

**Issue by rvbg** [GitBib/pymkv2#2]
**Is your enhancement request related to a problem? Please describe.**
Using the mkvmerge_path parameter (for example in verify_mkvmerge) can be limiting, if mkvmerge is not directly accessible and needs parameters to run.

One example would be `flatpak run org.bunkus.mkvtoolnix-gui mkvmerge`.

The subprocess function (in pymkv/Verifications.py line 20) would not accept this:
`sp.check_output(['flatpak run org.bunkus.mkvtoolnix-gui mkvmerge', '-V']).decode()`

It would be necessary to append to the list, to have something like that:
`sp.check_output(['flatpak', 'run', 'org.bunkus.mkvtoolnix-gui', 'mkvmerge', '-V']).decode()`

**Describe the solution you'd like**
It would be great to have a parameter with a list of strings for the mkvmerge path.
It could also be some sort of function to split the str into a list, which then gets appended to the subprocess function parameter.

**Implementation steps**
 - [ ] Find all functions with a mkvmerge_path parameter.
 - [ ] Replace/add a new parameter which would allow to use a list (or something similar).

**Additional context**

**Comment by GitBib** [comment]
This is a great improvement. I'll try to include it along with adding types and releasing the new version.

**Comment by GitBib** [comment]
Added a middleware layer that will split the path and handle it correctly. https://github.com/GitBib/pymkv2/pull/1/commits/e96ad520be9cf6eb235c3397a935fe9f6a28cdef

**Comment by GitBib** [comment]
Implemented in version [2.0.3](https://github.com/GitBib/pymkv2/releases/tag/2.0.3).

**Comment by rvbg** [comment]
I will check it out immediately. Thank you so much for your work!

**Comment by GitBib** [comment]
It would be cool and convenient to write tests for GitHub Actions based on Flatpak.

**Comment by GitBib** [comment]
Hope you’re doing well. I’m going to close this issue. If you have any questions, feel free to reopen it.
