### ISSUE TITLE
Error: The file '--hearing-impaired-flag' could not be opened for reading: open file error.

### ISSUE THREAD

**Issue by GuyMicciche** [GitBib/pymkv2#22]
I get this error message: 

`Error: The file '--hearing-impaired-flag' could not be opened for reading: open file error.`

When trying to convert a video in Linux. 

My setup is I have a Python Web App hosted in Azure. I develop it in Windows and it works on my machine. I get the encoded .mkv file. However when upload my app to Azure, I get this error message. Am I missing something here? Is there something different I need to setup for working on Linux? I have Chinese characters for naming my tracks: 
 
```
mkv.add_track(MKVTrack(temp_srt_en.name, language="eng", track_name="English"))
mkv.add_track(MKVTrack(temp_srt_chs.name, language="chi", track_name="中文"))
mkv.add_track(MKVTrack(temp_srt_pinyin.name, language="chi", track_name="Pīnyīn"))
```

Don't know what the issue is exactly difficult to diagnose since I'm developing on a Windows box

**Comment by GitBib** [comment]
Hey, the error shows the full path to the file that `pymkv2` is trying to open. You might wanna check what's in your `temp_srt` variable... chances are, the problem's there.

**Comment by GitBib** [comment]
Got a feeling this problem was connected to that one #23 .
