### ISSUE TITLE
string path with space isn't supported

### ISSUE THREAD

**Issue by starman2021** [GitBib/pymkv2#23]
In utils\prepare_mkvtoolnix_path   (pymkv2 2.0.7)

shlex.split turns a windows path with a space into 2 items in the list.

I modified elif as follows to print the path and shlex result, and then just return the string path as a list.  This made my first use of the module possible.

    if isinstance(path, os.PathLike):
        return [os.fspath(path)]
    elif isinstance(path, str) :
        print(f"{path=}")
        print(f"{shlex.split(path)=}")
        # return shlex.split(path)
        return [path]
Output:
path='C:\\Program Files\\MKVToolNix\\mkvmerge.exe'
shlex.split(path)=['C:Program', 'FilesMKVToolNixmkvmerge.exe']

**Software (please complete the following information):**
- os win7 64bit
- mkvtoolniv v60

**Comment by GitBib** [comment]
Interesting bug. I'll need to find a Windows computer to check it out and fix it.

**Comment by starman2021** [comment]
Under linux:

Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shlex
>>> shlex.split("/home/bob/dir with space/mkv/mkvmerge")
['/home/bob/dir', 'with', 'space/mkv/mkvmerge']

If the string is quoted, it returns a single item - but 

I'll do a pull? request and take care of that and help with the messages when a path isn't found.  I've had lots of challenges with modules that wrap executables!

**Comment by starman2021** [comment]
closed by accident.

**Comment by GitBib** [comment]
If they manage to fix it by the weekend, I'd be happy to see a pull request.

**Comment by GitBib** [comment]
Spent some time testing different scenarios—uploaded the most accurate and correct one. #24

**Comment by GitBib** [comment]
Hey @starman2021, did the current solution help with your problem?
